### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by AdamYLiang** [wieczorekc18/BluTube#2]
**Likes** 
- [x] Make likes a polymorphic association. That way you can have one table that is able to handle both video likes and comment likes. See here for more information : https://guides.rubyonrails.org/association_basics.html#polymorphic-associations

**Tags**
- [x] Tags can be a bonus MVP
- [x] Tags should be a broken up into a tag/video join table since it is a many-to-many relationship. 

Let me know if you have any questions.

**Comment by wieczorekc18** [comment]
Made changes not that confident on the tag/video join table lmk if it's ok or not 
-Thanks Adam
